  version: '1'

  services:
    atis150-php:
      build:
        context: .
        dockerfile: config/Dockerfile
      image: atis150/zapocet:v1
      expose:
        - 9000
      volumes:
        - ./src:/var/www/html

    atis150-web:
      image: library/nginx:1.20.1
      ports:
        - "8086:80"
      depends_on:
        - atis150-php
      volumes:
        - ./src:/var/www/html
        - ./config/default.conf:/etc/nginx/conf.d/default.conf